Changing Github action install-pip-modules

diff --git a/.github/actions/install-pip-modules/action.yml b/.github/actions/install-pip-modules/action.yml
--- a/.github/actions/install-pip-modules/action.yml
+++ b/.github/actions/install-pip-modules/action.yml
@@ -12,10 +12,6 @@ inputs:
     description: Should linter tools like pylint, flake8, shellcheck a.s.o be installed.
     required: false
     default: false
-  use_poetry:
-    description: Use poetry for ensuring the dependencies
-    required: false
-    default: true
 
 runs:
   using: "composite"
@@ -30,72 +26,75 @@ runs:
       id: pip-upgrade
       shell: bash
       run: |
+        echo ""
         echo "Upgrading Pip."
         pip install --upgrade pip
     - name: Install Python Requirements
-      env:
-        USE_POETRY: ${{ inputs.use_poetry }}
       id: inst-requirements
-      shell: bash
-      run: |
-        if [[ "${USE_POETRY}" != true ]] ; then
-            echo "Updating all Python modules by requirements.txt ..."
-            if [[ -f requirements.txt ]] ; then
-                  pip install --upgrade --upgrade-strategy eager --requirement requirements.txt
-            else
-                  echo "File 'requirements.txt' not found."
-            fi
-        else
-            echo "Installing poetry with pip ..."
-            pip install poetry
-            echo "Installing all necessary packages with poetry ..."
-            poetry install --no-root --ansi
-        fi
-    - name: Install Pytest
       env:
         INSTALL_PYTEST: ${{ inputs.install_pytest }}
-        USE_POETRY: ${{ inputs.use_poetry }}
-      id: inst-pytest
-      shell: bash
-      run: |
-        if [[ "${USE_POETRY}" != true ]] ; then
-            echo "Installing pytest by pip"
-            if [[ "${INSTALL_PYTEST}" != false ]] ; then
-                pip install --upgrade --upgrade-strategy eager pytest
-            else
-                echo "Installing pytest not necessary."
-            fi
-        fi
-    - name: Install Linter tools
-      env:
         INSTALL_LINTER_TOOLS: ${{ inputs.install_linter_tools }}
-        USE_POETRY: ${{ inputs.use_poetry }}
-      id: inst-linter-tools
       shell: bash
       run: |
-        if [[ "${INSTALL_LINTER_TOOLS}" == false ]] ; then
-            echo "Installation of Linter tools not necessary."
-        else
-            echo "Installing shellcheck and yamllint ..."
-            if type -p apt >/dev/null; then
-                apt install --yes shellcheck yamllint
-            elif type -p dnf >/dev/null; then
-                dnf --assumeyes install ShellCheck yamllint
-            elif type -p yum >/dev/null; then
-                yum --assumeyes install ShellCheck yamllint
-            else
-                echo "Did not found apt, dnf or yum." >&2
-                exit 5
-            fi
-            if [[ "${USE_POETRY}" != true ]] ; then
-                echo "Installing flake8 and pylint ..."
-                pip install --upgrade --upgrade-strategy eager flake8 pylint
-                if [[ -f requirements-lint.txt ]] ; then
-                    echo "Installing PIP requirements from requirements-lint.txt ..."
-                    pip install --upgrade --upgrade-strategy eager --requirement requirements-lint.txt
-                fi
-            fi
+        echo ""
+        echo "Installing poetry with pip ..."
+        pip install poetry
+        echo ""
+        echo "Installing all necessary packages with poetry ..."
+        POETRY_OPTS='--no-root --ansi'
+        if [[ "${INSTALL_PYTEST}" != false ]] ; then
+            POETRY_OPTS+=" --only=test"
         fi
+        if [[ "${INSTALL_LINTER_TOOLS}" == false ]] ; then
+            POETRY_OPTS+=" --only=dev"
+        fi
+        echo "Poetry install options: '${POETRY_OPTS}'"
+        poetry install ${POETRY_OPTS}
+    # - name: Install Pytest
+    #   env:
+    #     INSTALL_PYTEST: ${{ inputs.install_pytest }}
+    #     USE_POETRY: ${{ inputs.use_poetry }}
+    #   id: inst-pytest
+    #   shell: bash
+    #   run: |
+    #     if [[ "${USE_POETRY}" != true ]] ; then
+    #         echo "Installing pytest by pip"
+    #         if [[ "${INSTALL_PYTEST}" != false ]] ; then
+    #             pip install --upgrade --upgrade-strategy eager pytest
+    #         else
+    #             echo "Installing pytest not necessary."
+    #         fi
+    #     fi
+    # - name: Install Linter tools
+    #   env:
+    #     INSTALL_LINTER_TOOLS: ${{ inputs.install_linter_tools }}
+    #     USE_POETRY: ${{ inputs.use_poetry }}
+    #   id: inst-linter-tools
+    #   shell: bash
+    #   run: |
+    #     if [[ "${INSTALL_LINTER_TOOLS}" == false ]] ; then
+    #         echo "Installation of Linter tools not necessary."
+    #     else
+    #         echo "Installing shellcheck and yamllint ..."
+    #         if type -p apt >/dev/null; then
+    #             apt install --yes shellcheck yamllint
+    #         elif type -p dnf >/dev/null; then
+    #             dnf --assumeyes install ShellCheck yamllint
+    #         elif type -p yum >/dev/null; then
+    #             yum --assumeyes install ShellCheck yamllint
+    #         else
+    #             echo "Did not found apt, dnf or yum." >&2
+    #             exit 5
+    #         fi
+    #         if [[ "${USE_POETRY}" != true ]] ; then
+    #             echo "Installing flake8 and pylint ..."
+    #             pip install --upgrade --upgrade-strategy eager flake8 pylint
+    #             if [[ -f requirements-lint.txt ]] ; then
+    #                 echo "Installing PIP requirements from requirements-lint.txt ..."
+    #                 pip install --upgrade --upgrade-strategy eager --requirement requirements-lint.txt
+    #             fi
+    #         fi
+    #     fi
     - name: Show installed Python modules
       id: show-py-modules
       env:
